version: '3'

services:
  osm:
    build:
      context: .
      dockerfile: ./Openstreetmap/Dockerfile
    image: "openstreetmap:latest"
    ports:
      - 8081:80
      - 5432:5432
    environment:
      - HOST= 0.0.0.0
